import createGitHubJWT from "../github/createGithubJWT";
import axios from "axios";

const INSTALLATION_ID = process.env.GITHUB_INSTALLATION_ID!;

const GITHUB_API = "https://api.github.com";

async function getInstallationToken(): Promise<string> {
  const jwtToken = createGitHubJWT();
  const res = await axios.post(
    `${GITHUB_API}/app/installations/${INSTALLATION_ID}/access_tokens`,
    {},
    {
      headers: {
        Authorization: `Bearer ${jwtToken}`,
        Accept: "application/vnd.github+json",
      },
    }
  );
  return res.data.token;
}

async function getDefaultBranch(
  token: string,
  owner: string,
  repo: string
): Promise<string> {
  const res = await axios.get(`${GITHUB_API}/repos/${owner}/${repo}`, {
    headers: { Authorization: `token ${token}` },
  });
  return res.data.default_branch;
}

async function getBranchSHA(
  token: string,
  owner: string,
  repo: string,
  branch: string
): Promise<string> {
  const res = await axios.get(
    `${GITHUB_API}/repos/${owner}/${repo}/git/ref/heads/${branch}`,
    {
      headers: { Authorization: `token ${token}` },
    }
  );
  return res.data.object.sha;
}

async function createBranch(
  token: string,
  owner: string,
  repo: string,
  newBranch: string,
  sha: string
) {
  await axios.post(
    `${GITHUB_API}/repos/${owner}/${repo}/git/refs`,
    {
      ref: `refs/heads/${newBranch}`,
      sha,
    },
    {
      headers: { Authorization: `token ${token}` },
    }
  );
}

async function commitDockerfile(
  token: string,
  owner: string,
  repo: string,
  branch: string,
  content: string
) {
  const encoded = Buffer.from(content).toString("base64");
  await axios.put(
    `${GITHUB_API}/repos/${owner}/${repo}/contents/Dockerfile`,
    {
      message: "Add Dockerfile via AI",
      content: encoded,
      branch,
    },
    {
      headers: { Authorization: `token ${token}` },
    }
  );
}

async function createPR(
  token: string,
  owner: string,
  repo: string,
  branch: string,
  base: string
) {
  const res = await axios.post(
    `${GITHUB_API}/repos/${owner}/${repo}/pulls`,
    {
      title: "Add Dockerfile (auto-generated)",
      head: branch,
      base,
      body: "This PR adds a Dockerfile generated by our PaaS.",
    },
    {
      headers: { Authorization: `token ${token}` },
    }
  );
  return res.data.html_url;
}

export async function handleDockerfilePR(
  owner: string,
  repo: string,
  dockerfileContent: string
): Promise<string> {
  const token = await getInstallationToken();
  const baseBranch = await getDefaultBranch(token, owner, repo);
  const baseSha = await getBranchSHA(token, owner, repo, baseBranch);
  const newBranch = `auto/dockerfile-${Date.now()}`;
  await createBranch(token, owner, repo, newBranch, baseSha);
  await commitDockerfile(token, owner, repo, newBranch, dockerfileContent);
  const prUrl = await createPR(token, owner, repo, newBranch, baseBranch);
  return prUrl;
}
